config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :disasters do 
  	resources :commets
  end

  root to: 'disasters#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :disasters
end

app/models/commet.rb
class Commet < ApplicationRecord
	belongs_to :disaster
	belongs_to :user
end

app/models/disaster.rb
class Disaster < ApplicationRecord
	belongs_to :category
	belongs_to :user
	has_many :commets
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :disasters
  has_many :commets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/commets_controller.rb
class CommetsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]

	def create
		disaster = Disaster.find(params[:disaster_id])
		comment = Commet.new(comment_params)
		comment.disaster = disaster
		comment.user = current_user
		comment.save
		redirect_to disaster_path(disaster)
	end

	def destroy
		disaster = Disaster.find(params[:disaster_id])
		comment = Commet.find(params[:id])
		comment.destroy
		redirect_to disaster_path(disaster)
	end

	private

		def comment_params
			params.require(:commet).permit(:speaker, :content, :disaster_id)
		end
end

app/controllers/disasters_controller.rb
class DisastersController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]

	def index
		@disasters = Disaster.all
		if params[:id]
			@disaster = Disaster.find(params[:id])
		else
			@disaster = Disaster.new
		end
	end

	def create
		disaster = Disaster.new(disaster_params)
		disaster.user = current_user
		disaster.save
		redirect_to disasters_path
	end

	def show
		@disaster = Disaster.find(params[:id])
		@comments = @disaster.commets
		@comment = Commet.new
	end

	def update
		disaster = Disaster.find(params[:id])
		disaster.update(disaster_params)
		redirect_to disasters_path
	end

	def destroy
		disaster = Disaster.find(params[:id])
		disaster.destroy
		redirect_to disasters_path
	end

	private 

		def disaster_params
			params.require(:disaster).permit(:title, :content, :category_id)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commets_helper.rb
module CommetsHelper
end

app/helpers/disasters_helper.rb
module DisastersHelper
end

app/views/disasters/index.html.erb
<%= form_for @disaster do |f| %>
	<%= f.label :title, "標題" %>
	<%= f.text_field :title %>

	<%= f.label :content, "內容" %>
	<%= f.text_area :content %>
	
	<%= f.label :category_id, "分類" %>
	<%= f.select :category_id, Category.all.collect {|c| [c.name, c.id]} %>

	<%= f.submit %>

<% end %>

<ul>
	<% @disasters.each do |disaster| %>
		<li>
			<%= link_to disaster.title, disaster_path(disaster) %>
			<%= disaster.created_at %>
			<%= link_to "編輯", disasters_path(id: disaster.id) if disaster.user == current_user %>
			<%= link_to "刪除", disaster_path(disaster), method: :delete if disaster.user == current_user %>
		</li>
	<% end %>
</ul>

app/views/disasters/show.html.erb
<%= link_to "Back", disasters_path %><br>
分類：<%= @disaster.category.name %><br>
標題：<%= @disaster.title %><br>
內容：<%= @disaster.content%><br>

<div>留言：</div>
<ul>
	<% @comments.each do |comment| %>
		<li>
			<%= comment.speaker %> : 
			<%= comment.content %>
			<%= link_to "刪除", disaster_commet_path(@disaster, comment), method: :delete if comment.user == current_user%>
		</li>
	<% end %>
</ul>

<%= form_for [@disaster, @comment], url: disaster_commets_path(@disaster) do |f| %>
	<%= f.label :speaker, "名字" %>
	<%= f.text_field :speaker %>

	<%= f.label :content, "留言" %>
	<%= f.text_area :content %>

	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Midterm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% if current_user %>
    	<%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
    	<%= link_to('修改密碼', edit_registration_path(:user)) %>
  	<% else %>
    	<%= link_to('註冊', new_registration_path(:user)) %> |
   	 <%= link_to('登入', new_session_path(:user)) %>
  	<% end %>
		<br>
  	<p class="notice"><%= notice %></p>
  	<p class="alert"><%= alert %></p>
		<br>
    <%= yield %>
  </body>
</html>